version: '3'
services:

  frontend:
    build: react
    volumes:
        - ./react:/usr/src/app
    command: sh -c "cd react-app && yarn start"
    ports:
        - "3000:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M

  backend:
    build: rails
    env_file:
      - ./.rails.env
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 250M

  db:
    build: mysql
    env_file:
      - ./.db.env
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 350M
  
  web:
    build: nginx
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./react/react-app/build:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
    volumes_from:
      # - frontend
      - backend
    depends_on:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
  